# Solving Fizz Buzz using machine learning
This topic is inspired by one of Joel Grus's blog: [Fizz Buzz in Tensorflow](https://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/ "With a Title"), where he gives a funny story about solving this simple algorithmic interview question using neuron networks. In this topic, we gonna repeat this calculating process using Keras and other machine learning classifiers as practice.


In [1]:
import numpy as np

In [4]:
a = 14

In [42]:
b = '{:010b}'.format(a)

In [47]:
b

'0000001110'

In [60]:
c = np.array(list(b))


In [58]:
c

array(['0', '0', '0', '0', '0', '0', '1', '1', '1', '0'], dtype='<U1')

In [59]:
c[0]

'0'

In [2]:
start = 101
end = 1023
length = end - start + 1
numbers = np.zeros([length, 10])
for i in range(0, length):
    number = '{:010b}'.format(i + start)
    number = np.array(list(number))
    numbers[i] = number

In [63]:
numbers.shape

(923, 10)

In [64]:
numbers[2]

array([0., 0., 0., 1., 1., 0., 0., 1., 1., 1.])

In [67]:
numbers[921]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])

In [3]:
labels = np.zeros([length])
for i in range(0, length):
    number = i + start
    if number%15 == 0:
        labels[i] = 3
    elif number%3 == 0:
        labels[i] = 1
    elif number%5 == 0:
        labels[i] = 2
    else:
        labels[i] ==0

In [71]:
labels[922]

1.0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(numbers, labels, test_size=0.20, random_state=102)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.optimizers import SGD, Adam, Adagrad
from tensorflow.keras.utils import to_categorical

In [8]:
y_train_cate = to_categorical(y_train, 4)

In [8]:
y_test[1]

0.0

In [93]:
y_test[3]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [9]:
model = Sequential()
model.add(Dense(input_dim = 10, units = 1000, activation = 'relu'))
#model.add(Dropout(0.3))
model.add(Dense(units=1000, activation='relu'))
#model.add(Dropout(0.3))
model.add(Dense(units=4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['acc'])

In [10]:
model.fit(X_train, y_train_cate, batch_size=10, epochs=100)

#model.fit(X_train, y_train, batch_size=20, epochs=50)

Train on 738 samples
Epoch 1/100
738/738 [==============================] - 1s 1ms/sample - loss: 1.2097 - acc: 0.5068
Epoch 2/100
738/738 [==============================] - 0s 336us/sample - loss: 1.1737 - acc: 0.5285
Epoch 3/100
738/738 [==============================] - 0s 324us/sample - loss: 1.1502 - acc: 0.5285
Epoch 4/100
738/738 [==============================] - 0s 316us/sample - loss: 1.1314 - acc: 0.5257
Epoch 5/100
738/738 [==============================] - 0s 324us/sample - loss: 1.0987 - acc: 0.5271
Epoch 6/100
738/738 [==============================] - 0s 327us/sample - loss: 1.0333 - acc: 0.5244
Epoch 7/100
738/738 [==============================] - 0s 325us/sample - loss: 0.9513 - acc: 0.5664
Epoch 8/100
738/738 [==============================] - 0s 333us/sample - loss: 0.8256 - acc: 0.6477
Epoch 9/100
738/738 [==============================] - 0s 323us/sample - loss: 0.6190 - acc: 0.7818
Epoch 10/100
738/738 [==============================] - 0s 326us/sample - loss: 0

In [11]:
from sklearn.metrics import confusion_matrix, classification_report
predicted = model.predict_classes(X_test)
confusion_matrix(predicted, y_test)

array([[99,  6,  2,  1],
       [ 4, 43,  3,  0],
       [ 0,  0, 21,  0],
       [ 0,  0,  0,  6]], dtype=int64)

In [12]:
print(classification_report(predicted, y_test))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       108
           1       0.88      0.86      0.87        50
           2       0.81      1.00      0.89        21
           3       0.86      1.00      0.92         6

    accuracy                           0.91       185
   macro avg       0.88      0.94      0.91       185
weighted avg       0.92      0.91      0.91       185



In [13]:
print(X_test[1])

[1. 1. 0. 0. 1. 0. 1. 1. 0. 0.]


In [14]:
start = 0
end = 100
length = end - start + 1

ans = np.zeros([length, 10])
for i in range(0, length):
    number = '{:010b}'.format(i + start)
    number = np.array(list(number))
    ans[i] = number

answer = model.predict_classes(ans)
output = []
for i in range(100):
    if answer[i] == 3:
        output = np.append(output, 'FizzBuzz')
    elif answer[i] == 1:
        output = np.append(output, 'Fizz')
    elif answer[i] == 2:
        output = np.append(output, 'Buzz')
    else:
        output = np.append(output, str(i))
print(output)

['Buzz' '1' '2' 'Fizz' '4' '5' 'Fizz' '7' '8' 'Fizz' 'Buzz' '11' 'Fizz'
 '13' '14' 'FizzBuzz' '16' '17' 'Fizz' '19' 'Buzz' '21' '22' '23' 'Fizz'
 '25' '26' 'Fizz' '28' '29' 'FizzBuzz' '31' '32' 'Fizz' '34' 'Buzz' 'Fizz'
 '37' '38' 'Fizz' 'Buzz' '41' 'Fizz' '43' '44' 'FizzBuzz' '46' '47' 'Fizz'
 '49' 'Buzz' 'Fizz' '52' '53' 'Fizz' 'Buzz' '56' 'Fizz' '58' '59'
 'FizzBuzz' '61' '62' 'Fizz' '64' 'Buzz' 'Fizz' '67' '68' 'Fizz' 'Buzz'
 '71' 'Fizz' '73' '74' 'FizzBuzz' '76' '77' 'Fizz' '79' '80' '81' '82'
 '83' 'Fizz' 'Buzz' '86' 'Fizz' '88' '89' 'FizzBuzz' '91' '92' 'Fizz' '94'
 'Buzz' 'Fizz' '97' '98' 'Fizz']


In [15]:
labels = np.zeros([length])
for i in range(0, length):
    number = i + start
    if number%15 == 0:
        labels[i] = 3
    elif number%3 == 0:
        labels[i] = 1
    elif number%5 == 0:
        labels[i] = 2
    else:
        labels[i] ==0

In [16]:
confusion_matrix(answer, labels)

array([[53,  2,  3,  0],
       [ 0, 25,  0,  0],
       [ 0,  0, 11,  1],
       [ 0,  0,  0,  6]], dtype=int64)

### Now lets compare NN model with some other machine learning models.
We will try KNN, decision tree, randomForest and GBDT

In [153]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [167]:
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [177]:
svc = SVC(gamma='auto', C=100,  class_weight='balanced',kernel = 'sigmoid')

In [178]:
svc.fit(X_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [179]:
predicted_svc = svc.predict(X_test)
print(confusion_matrix(predicted_svc, y_test))
print(classification_report(predicted_svc, y_test))

[[41 24  7  0]
 [28 13  4  2]
 [13  4  6  1]
 [21  8  9  4]]
              precision    recall  f1-score   support

         0.0       0.40      0.57      0.47        72
         1.0       0.27      0.28      0.27        47
         2.0       0.23      0.25      0.24        24
         3.0       0.57      0.10      0.16        42

    accuracy                           0.35       185
   macro avg       0.37      0.30      0.29       185
weighted avg       0.38      0.35      0.32       185



In [45]:
y_train

array([1., 2., 1., 1., 0., 1., 0., 0., 1., 0., 3., 0., 0., 2., 2., 1., 0.,
       0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       3., 0., 0., 0., 1., 0., 2., 0., 0., 1., 0., 0., 2., 2., 1., 0., 2.,
       0., 2., 1., 1., 0., 0., 3., 2., 0., 0., 2., 3., 3., 0., 0., 1., 3.,
       1., 1., 0., 3., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 3., 0., 0., 0., 3., 2., 3., 1., 3., 0., 0., 1.,
       2., 1., 0., 1., 1., 0., 0., 0., 0., 3., 3., 0., 1., 1., 0., 0., 1.,
       2., 2., 1., 1., 1., 0., 2., 1., 0., 0., 1., 2., 0., 1., 2., 0., 0.,
       0., 0., 0., 0., 0., 0., 3., 0., 2., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 2., 1., 3., 0., 0., 0., 0., 1., 2., 1., 0., 1.,
       3., 0., 0., 1., 2., 0., 0., 1., 1., 3., 0., 0., 2., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 2., 2., 0., 1., 0., 1., 2., 1., 0., 1., 0.,
       0., 1., 2., 3., 0., 0., 0., 0., 1., 0., 3., 0., 1., 3., 0., 0., 1.,
       2., 2., 0., 0., 0.

In [72]:
np.unique(y_train, return_counts=True) 

(array([0., 1., 2., 3.]), array([390, 197,  96,  55], dtype=int64))